# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - clang++
 
# Build steps
script:
  - cd third_party
  - ./get_atl.sh 
  - cd ..
  - clang++ -std=c++11 -O3 main.cpp -o mas.x
